apiVersion: v1
kind: Service
metadata:
  name: preview
  namespace: deployment-engine
spec:
  type: NodePort
  selector:
    app: deployment-engine
    color: blue
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
    - name: metrics
      port: 9113
      targetPort: 9113
