apiVersion: v1
kind: Service
metadata:
  name: preview
  namespace: deployment-engine
spec:
  selector:
    app: deployment-engine
    color: blue
  ports:
    - name: http
      port: 80
      targetPort: 80
